# Generated by Django 5.0.3 on 2024-04-09 19:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(blank=True, error_messages='Please make sure your first_name contain only alphabelts', max_length=150, validators=[django.core.validators.RegexValidator('[a-zA-Z]+')], verbose_name='First name'),
        ),
    ]
