# Generated by Django 5.0.3 on 2024-04-09 19:49

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_newuser_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(blank=True, error_messages='Please make sure your first_name contain only alphabelts', max_length=150, validators=[base.models.NewUser.validator_alpha], verbose_name='First name'),
        ),
    ]
