# Generated by Django 5.0.3 on 2024-04-09 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_user_name_newuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='username',
            new_name='user_name',
        ),
    ]
