# Generated by Django 5.0.3 on 2024-05-08 18:55

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_user_name_newuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='posts/account_circle_48dp_FILL0_wght400_GRAD0_opsz48.png', upload_to=base.models.upload_to, verbose_name='Image'),
        ),
    ]
